# Generated by Django 4.1 on 2023-07-22 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_students_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_entries',
            name='subscription_start_date',
            field=models.DateTimeField(default=datetime.date(2023, 7, 23)),
        ),
    ]
