# Generated by Django 4.0.6 on 2024-05-29 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_subscription_entries_subscription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_entries',
            name='subscription_start_date',
            field=models.DateTimeField(default=datetime.date(2024, 5, 29)),
        ),
    ]
