# Generated by Django 4.0.5 on 2022-08-25 04:17

import datetime
from django.db import migrations, models
import uuid
from django.db.models import UUIDField
from django.db.models.functions import Cast

class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='temp_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunSQL(
            "UPDATE teachers_students SET temp_uuid = uuid_generate_v4();",
        ),
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='temp_uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription_entries',
            name='subscription_start_date',
            field=models.DateTimeField(default=datetime.date(2022, 8, 25)),
        ),
    ]